routes/web.php
<?php

use App\Http\Controllers\VideoTutsController;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\PolicyController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\ClaimController;
use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\LoginController;

use App\Http\Controllers\Clients\PoliciesController;
use App\Http\Controllers\Clients\BeneficieryController;
use App\Http\Controllers\Clients\ClaimsController;
use App\Http\Controllers\Clients\PaymentController;
use App\Http\Controllers\Clients\ProfileController;

use App\Http\Controllers\Agent\AgentCommisionsController;
use App\Http\Controllers\Agent\AgentDashboardController;
use App\Http\Controllers\Agent\AgentPoliciesController;

use App\Http\Controllers\Admin\AdminPoliciesController;
use App\Http\Controllers\Admin\AdminAgentsController;
use App\Http\Controllers\Admin\AdminClaimsController;
use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\Admin\AdminNotificationsController;
use App\Http\Controllers\Admin\AdminReportsController;
use App\Http\Controllers\Admin\AdminProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
//website_routes
Route::get('portal',[PortalController::class, 'index'])->name('portal');
Route::get('claims',[ClaimController::class, 'index'])->name('claims');
Route::get('myPolicy',[PolicyController::class, 'index'])->name('myPolicy');
Route::get('contact',[ContactController::class, 'index'])->name('contact');
Route::get('applications',[ApplicationController::class, 'index'])->name('applications');
Route::get('stepper_application',[ApplicationController::class, 'application'])->name('stepper_application');
Route::get('stepper-application',[ApplicationController::class, 'adminMail'])->name('stepper-application');
Route::post('adminMail',[ApplicationController::class, 'adminMail'])->name('admin-mail');

Auth::routes(['verify' => true]);
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('products', ProductController::class);
});


//client_routes
Route::get('clients/policy',[PoliciesController::class, 'index'])->name('clients/policy');
Route::get('clients/beneficiaries',[BeneficieryController::class, 'index'])->name('clients/beneficiaries');
Route::get('clients/payments',[PaymentController::class, 'index'])->name('clients/payments');
Route::get('clients/profile',[ProfileController::class, 'index'])->name('clients/profile');
Route::get('clients/claims',[ClaimsController::class, 'index'])->name('clients/claims');
Route::get('clients/claimForm',[ClaimsController::class, 'getClaimForm'])->name('clients/claimForm');
Route::post('clients/claimForm',[ClaimsController::class, 'captureClaims'])->name('claims.store');

//agent_routes
Route::get('agents/dashboard',[AgentDashboardController::class, 'index'])->name('agents/dashboard');
Route::get('agents/policy',[AgentPoliciesController::class, 'index'])->name('agents/policy');
Route::get('agents/commissions',[AgentCommisionsController::class, 'index'])->name('agents/commissions');
Route::get('agents/tutorials',[VideoTutsController::class, 'index'])->name('agents/tutorials');
Route::get('register',[RegisterController::class, 'index'])->name('register');
Route::get('login',[LoginController::class, 'index'])->name('login');

//admin_routes
Route::get('admin/dashboard',[AdminDashboardController::class, 'index'])->name('admin/dashboard');
Route::get('admin/policies',[AdminPoliciesController::class, 'index'])->name('admin/policies');
Route::get('admin/agents',[AdminAgentsController::class, 'index'])->name('admin/agents');
Route::get('admin/claims',[AdminClaimsController::class, 'index'])->name('admin/claims');
Route::get('admin/reports',[AdminReportsController::class, 'index'])->name('admin/reports');
Route::get('admin/notifications',[AdminNotificationsController::class, 'index'])->name('admin/notifications');
Route::get('admin/profile',[AdminProfileController::class, 'index'])->name('admin/profile');
Route::post('policy-filter',[AdminPoliciesController::class, 'filterByDate'])->name('policy-filter');
Route::get('clear-search',[AdminPoliciesController::class, 'clrSearch'])->name('clear-search');
Route::get('admin/delete/{id}',[AdminPoliciesController::class, 'destroy'])->name('admin/delete');
Route::get('admin/show/{id}',[AdminPoliciesController::class, 'show'])->name('admin/show');
Route::get('admin/edit/{id}',[AdminPoliciesController::class, 'show_stepper'])->name('admin/edit');
Route::post('admin/add-video',[VideoTutsController::class, 'store'])->name('admin/update-video');
Route::post('admin/update-video',[VideoTutsController::class, 'update'])->name('admin/add-video');
Route::get('admin/tutorials',[VideoTutsController::class, 'videoTuts'])->name('admin/tutorials');
Route::get('admin/delete-video/{id}',[VideoTutsController::class, 'deleteVideo'])->name('admin/delete-video');
Route::get('admin/show-video/{id}',[VideoTutsController::class, 'showVideo'])->name('admin/show-video');

resources/views/patials/footer.blade.php
<footer class="footer-area">
    <div class="container">
        <div class="subscribe-area">
            <div class="row align-items-center">
                <div class="col-lg-5 col-md-12">
                    <div class="subscribe-content">
                        <h2>CALL ME BACK</h2>
                        <p>Complete the form below and one of our friendly consultants will call you back for a quote.</p>
                    </div>
                </div>
                <div class="col-lg-7 col-md-12">
                    <div class="subscribe-form">
                        <form class="newsletter-form" data-toggle="validator">
                            <input type="email" class="input-newsletter" placeholder="Enter your phone number" name="EMAIL" required autocomplete="off">
                            <button type="submit">CALL ME BACK <i class="flaticon-right-chevron"></i></button>
                            <div id="validator-newsletter" class="form-result"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <div class="logo">
                        <a href="#"><img src="{{asset('public/frontend/img/log.png')}}" alt="image"></a>
{{--                        <p>Atlantic Funeral Service and Burial Fund are an Authorised Financial Services Provider--}}
{{--                            in terms of section 8 of the financial advisory and intermediary services act,--}}
{{--                            2002 (Act No. 37 of 2002) subject to the conditions and restrictions set out in--}}
{{--                            the Annexure. Atlantic Funeral Service has been in existence since 1st August 2001--}}
{{--                            and has over 20 years experience in the funeral industry.--}}

{{--                        </p>--}}
                    </div>
                    <ul class="social">
                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                        <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h3>Quick Links</h3>
                    <ul class="footer-quick-links">
                        <li><a href="{{url('/')}}">Home</a></li>
                        <li><a href="{{url('/')}}">Our Team</a></li>
                        <li><a href="{{url('/')}}">About Us</a></li>
                        <li><a href="{{url('/')}}">Our Packages</a></li>
                        <li><a href="{{url('/login')}}">My Policy</a></li>
                        <li><a href="{{url('/')}}">Contact Us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-0 offset-sm-3 offset-md-3">
                <div class="single-footer-widget">
                    <h3>Contact Info</h3>
                    <ul class="footer-contact-info">
                        <li><span>Location:</span> 16 Soldaat Plein, Factreton, Cape Town</li>
                        <li><span>Email:</span> <a href="#"><span class="__cf_email__" data-cfemail="29594c485b46694e44484045074a4644">info@atlanticfunerals.co.za</span></a></li>
                        <li><span>Phone:</span> <a href="#">+(27) 844478850</a></li>
                      </ul>
                </div>
            </div>
        </div>
        <div class="copyright-area">
            <div class="row align-items-center">
                <div class="col-lg-8 col-sm-8 col-md-8">
                    <p>Copyright ©<script>document.write(new Date().getFullYear());</script>  Atlantic Funerals. All Rights Reserved. Designed by Shifttech Global Solutions</p>

                </div>
                <div class="col-lg-4 col-sm-4 col-md-4">
                    <ul>
                        <li><a href="contact.html">Privacy Policy</a></li>
                        <li><a href="contact.html">Terms & Conditions</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/patials/header.blade.php
<header class="header-area">

    <div class="top-header">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-5 col-md-12">
                    <ul class="top-header-nav">
                        <li><a href="#">COVID-19 Updates</a></li>

                        <li><a href="#">Our App</a></li>

                    </ul>
                </div>
                <div class="col-lg-7 col-md-12">
                    <div class="top-header-right-side">
                        <ul>
                            <li>
                                <div class="icon">
                                    <i class="flaticon-email"></i>
                                </div>
                                <span>Drop us an email:</span>
                                <a href="#"><span>info@atlanticfunerals.co.za</span></a>
                            </li>
                            <li>
                                <div class="icon">
                                    <i class="flaticon-call"></i>
                                </div>
                                <span>Call us:</span>
                                <a href="#">+27 84447 8850</a>
                            </li>
                            <li>
                                <a href="{{url('/login')}}" class="default-btn">LOGIN<span></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="navbar-area">
        <div class="pearo-responsive-nav">
            <div class="container">
                <div class="pearo-responsive-menu">
                    <div class="logo">
                        <a href="{{url('/')}}">
                            <img src="{{asset('public/frontend/img/logo.png')}}" alt="logo">
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="pearo-nav">
            <div class="container">
                <nav class="navbar navbar-expand-md navbar-light">
                    <a class="navbar-brand" href="{{url('/')}}">
                        <img src="{{asset('public/frontend/img/log.png')}}" alt="logo">
                    </a>
                    <div class="collapse navbar-collapse mean-menu" id="navbarSupportedContent">
                        <ul class="navbar-nav">
                            {{--                            <li class="nav-item"><a href="{{url('/')}}" class="nav-link active">Home <i class="flaticon-down-arrow"></i></a>--}}
                            {{--                                <ul class="dropdown-menu">--}}
                            {{--                                    <li class="nav-item"><a href="index.html" class="nav-link active">Home One</a></li>--}}
                            {{--                                    <li class="nav-item"><a href="index-2.html" class="nav-link">Home Two</a></li>--}}
                            {{--                                    <li class="nav-item"><a href="index-3.html" class="nav-link">Home Three</a></li>--}}
                            {{--                                    <li class="nav-item"><a href="index-4.html" class="nav-link">Home Four</a></li>--}}
                            {{--                                </ul>--}}
                            {{--                            </li>--}}


                            <li class="nav-item"><a href="#" class="nav-link">Products <i class="flaticon-down-arrow"></i></a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item"><a href="{{url('/')}}" class="nav-link">FUNERAL POLICIES</a></li>
                                    <li class="nav-item"><a href="{{url('/')}}" class="nav-link">FUNERAL ARRANGEMENTS</a></li>
                                    <li class="nav-item"><a href="{{url('/')}}" class="nav-link">CREMATIONS</a></li>
                                    <li class="nav-item"><a href="{{url('/')}}" class="nav-link">CASH FUNERALS</a></li>
                                    <li class="nav-item"><a href="{{url('/')}}" class="nav-link">TOMBSTONES</a></li>

                                </ul>
                            </li>
                            <li class="nav-item"><a href="{{url('/claims')}}" class="nav-link">Claims</a></li>

                            <li class="nav-item"><a href="{{url('/myPolicy')}}" class="nav-link">My Policy</a></li>
                            <li class="nav-item"><a href="{{url('/contact')}}" class="nav-link">Contact Us</a></li>

                        </ul>
                        <div class="others-option">
                            {{--                            <div class="option-item">--}}
                            {{--                                <i class="search-btn flaticon-search"></i>--}}
                            {{--                                <i class="close-btn flaticon-cross-out"></i>--}}
                            {{--                                <div class="search-overlay search-popup">--}}
                            {{--                                    <div class='search-box'>--}}
                            {{--                                        <form class="search-form">--}}
                            {{--                                            <input class="search-input" name="search" placeholder="Search" type="text">--}}
                            {{--                                            <button class="search-button" type="submit"><i class="flaticon-search"></i></button>--}}
                            {{--                                        </form>--}}
                            {{--                                    </div>--}}
                            {{--                                </div>--}}
                            {{--                            </div>--}}
{{--                            <div class="burger-menu">--}}
{{--                                <i class="flaticon-menu"></i>--}}
{{--                            </div>--}}
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>

</header>
<div class="sidebar-modal">
    <div class="sidebar-modal-inner">
        <div class="sidebar-about-area">
            <div class="title">
                <h2>About Us</h2>
                <p>We believe brand interaction is key in communication. Real innovations and a positive customer experience are the heart of successful communication. No fake products and services. The customer is king, their lives and needs are the inspiration.</p>
            </div>
        </div>
        <div class="sidebar-instagram-feed">
            <h2>Instagram</h2>
            <ul>
                <li><a href="single-blog.html"><img src="{{asset('public/frontend/img/blog-image/1.jpg')}}" alt="image"></a></li>
                <li><a href="single-blog.html"><img src="{{asset('public/frontend/img/blog-image/2.jpg')}}" alt="image"></a></li>
                <li><a href="single-blog.html"><img src="{{asset('public/frontend/img/blog-image/3.jpg')}}" alt="image"></a></li>
                <li><a href="single-blog.html"><img src="{{asset('public/frontend/img/blog-image/4.jpg')}}" alt="image"></a></li>

            </ul>
        </div>
        <div class="sidebar-contact-area">
            <div class="sidebar-contact-info">
                <div class="contact-info-content">
                    <h2>
                        <a href="tel:+0881306298615">+088 130 629 8615</a>
                        <span>OR</span>
                        <a href="https://templates.envytheme.com/cdn-cgi/l/email-protection#01716460736e41666c60686d2f626e6c"><span class="__cf_email__" data-cfemail="22524743504d62454f434b4e0c414d4f">[email&#160;protected]</span></a>
                    </h2>
                    <ul class="social">
                        <li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#" target="_blank"><i class="fab fa-youtube"></i></a></li>
                        <li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="#" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
                        <li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <span class="close-btn sidebar-modal-close-btn"><i class="flaticon-cross-out"></i></span>
    </div>
</div>

resources/views/patials/portalHeader.blade.php
    <div class="header">
        <div class="header-left">
            <a href="index.html" class="logo logo-small">
                <img src="{{asset('public/frontend/img/log.jpg')}}" alt="Logo" width="50" height="50">
            </a>
        </div>
        <a href="javascript:void(0);" id="toggle_btn">
            <i class="fas fa-align-left"></i>
        </a>
        <a class="mobile_btn" id="mobile_btn" href="javascript:void(0);">
            <i class="fas fa-align-left"></i>
        </a>
        <ul class="nav user-menu">

            <li class="nav-item dropdown noti-dropdown">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                    <i class="far fa-bell"></i> <span class="badge badge-pill"></span>
                </a>
            </li>


            <li class="nav-item dropdown">
                <a href="javascript:void(0)" class="dropdown-toggle user-link  nav-link" data-toggle="dropdown">
<span class="user-img">
<img class="rounded-circle" src="{{asset('public/frontend/img/log.jpg')}}" width="40" alt="Admin">
</span>
                </a>

                <div class="dropdown-menu dropdown-menu-right">

                    <a class="dropdown-item" href="admin-profile.html">Profile</a>
                    @if(Auth::user()->hasRole('Admin'))
                    <a class="dropdown-item" href="{{ route('users.index') }}">Manage Users</a>
                    <a class="dropdown-item" href="{{ route('roles.index') }}">Manage Role</a>

{{--                    <a class="dropdown-item" href="{{ route('products.index')}}">Manage Product</a>--}}
                    <a class="dropdown-item" href="" data-toggle="modal" data-target="#addVid">Upload Video Tutorial</a>
                    @endif



                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>


                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>


                </div>
            </li>

        </ul>
    </div>


    <div class="sidebar" id="sidebar">
        <div class="sidebar-logo">
            <a href="{{url('/home')}}">
                <img src="{{asset('public/frontend/img/log.png')}}" class="img-fluid" alt="">
            </a>
        </div>
        <div class="sidebar-inner slimscroll">
            <div id="sidebar-menu" class="sidebar-menu">
                    @if(Auth::user()->hasRole('Admin'))
                    <ul>
                        <li class="active">
                            <a href="{{url('/home')}}"><i class="fas fa-columns"></i> <span>Dashboard</span></a>
                        </li>
                        <li>
                            <a href="{{url('admin/policies')}}"><i class="fas fa-layer-group"></i> <span>Policies</span></a>
                        </li>
                        <li>
                            <a href="{{url('admin/claims')}}"><i class="fas fa-file-contract"></i> <span>Claims</span></a>
                        </li>
                        <li>
                            <a href="{{url('admin/agents')}}"><i class="fas fa-users"></i> <span> Agents</span></a>
                        </li>

                        <li>
                            <a href="{{url('admin/reports')}}"><i class="fas fa-file-archive"></i> <span>Reports</span></a>
                        </li>

                        <li>
                            <a href="{{url('admin/notifications')}}"><i class="fas fa-bell"></i> <span>Notifications</span></a>
                        </li>

                        <li>
                            <a href="{{url('admin/profile')}}"><i class="fas fa-user"></i> <span>Profile</span></a>
                        </li>
                        <li>
                            <a href="{{url('admin/tutorials')}}"><i class="fa fa-video"></i> <span>Video Tutorials</span></a>
                        </li>



                    </ul>
                        @endif
                    @if(Auth::user()->hasRole('Agent'))
                            <ul>
                                <li class="active">
                                    <a href="{{url('agents/dashboard')}}"><i class="fas fa-columns"></i> <span>Dashboard</span></a>
                                </li>
                                <li>
                                    <a href="{{url('agents/policy')}}"><i class="fas fa-layer-group"></i> <span>My Policies</span></a>
                                </li>
                                <li>
                                    <a href="{{url('agents/commissions')}}"><i class="fas fa-coins"></i> <span>Commissions</span></a>
                                </li>


                                <li>
                                    <a href="{{url('agents/profile')}}"><i class="fas fa-user"></i> <span>Profile</span></a>
                                </li>
                                <li>
                                    <a href="{{url('agents/tutorials')}}"><i class="fa fa-video"></i> <span>Video Tutorials</span></a>
                                </li>


                            </ul>
                        @endif
                    @if(Auth::user()->hasRole('Client'))
                            <ul>
                                <li class="active">
                                    <a href="{{url('/home')}}"><i class="fas fa-columns"></i> <span>Dashboard</span></a>
                                </li>
                                <li>
                                    <a href="{{url('clients/policy')}}"><i class="fas fa-id-card"></i> <span>My Policy</span></a>
                                </li>
                                <li>
                                    <a href="{{url('clients/claims')}}"><i class="fas fa-file-contract"></i> <span>My Claims</span></a>
                                </li>
{{--                                <li>--}}
{{--                                    <a href="{{url('clients/beneficiaries')}}"><i class="fas fa-users"></i> <span>My Beneficiaries</span></a>--}}
{{--                                </li>--}}

                                <li>
                                    <a href="{{url('clients/payments')}}"><i class="fas fa-money-bill"></i> <span>My Premiums</span></a>
                                </li>

                                <li>
                                    <a href="{{url('clients/profile')}}"><i class="fas fa-user"></i> <span>Profile</span></a>
                                </li>



                            </ul>
                    @endif
            </div>
        </div>
    </div>